module.exports = [
    {
        "domain": ".google.com",
        "expirationDate": 1549395897,
        "hostOnly": false,
        "httpOnly": false,
        "name": "1P_JAR",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "2019-1-6-19",
        "id": 1
    },
    {
        "domain": ".google.com",
        "expirationDate": 1609875892.852577,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "5wWxKSTJtDSPqb-e/AGA2SPAkw5b8V-onO",
        "id": 2
    },
    {
        "domain": ".google.com",
        "expirationDate": 2146723199.853394,
        "hostOnly": false,
        "httpOnly": false,
        "name": "CONSENT",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "YES+UA.ru+",
        "id": 3
    },
    {
        "domain": ".google.com",
        "expirationDate": 1609875892.852245,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AVLfnXNsylQe3YHpl",
        "id": 4
    },
    {
        "domain": ".google.com",
        "expirationDate": 1562615092.853252,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "154=HnLcKXQenlWEbl8XGcCvUksLBusGh6N4zEluWuZHSrphEI_iQYdXA1-WWhEPciHup83LNRsueAhmm3ZgT3Fl_9wZ_NEsCDzmsydDKxcRVmtuicPvYAFqNvIqzCPJufXz1BMuWj9MLDZ_-0F00m4mvmHiTyyBmRzHuaPQuiHCysw",
        "id": 5
    },
    {
        "domain": ".google.com",
        "expirationDate": 1609875892.852777,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "PAiLdWX4m1UaZEDL/Ale9MrQBHt-s5gitw",
        "id": 6
    },
    {
        "domain": ".google.com",
        "expirationDate": 1609875892.851701,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "6wbb6-drH7MMbZ_HovJDxNYKPBp5eD1jceJEbHAm94hCO_Uqw9un-v6UNmjFpooNGDRVcA.",
        "id": 7
    },
    {
        "domain": ".google.com",
        "expirationDate": 1554579903.945517,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "ABtHo-GdokCBmbQqdORtJkeNQSLuwR1rSSKpyWhkKgGFd4vjNDAgK_kFjOJyugS9hpb2QWbFiA",
        "id": 8
    },
    {
        "domain": ".google.com",
        "expirationDate": 1609875892.852391,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "A_JcjzIMaPtH7ucNZ",
        "id": 9
    },
    {
        "domain": ".keep.google.com",
        "expirationDate": 1609875904,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__utma",
        "path": "/u/0/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "40529592.1782938254.1545898150.1546794232.1546794650.25",
        "id": 10
    },
    {
        "domain": ".keep.google.com",
        "expirationDate": 1546805704,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__utmb",
        "path": "/u/0/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "40529592.17.9.1546803904091",
        "id": 11
    },
    {
        "domain": ".keep.google.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "__utmc",
        "path": "/u/0/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "40529592",
        "id": 12
    },
    {
        "domain": ".keep.google.com",
        "expirationDate": 1546804497,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__utmt",
        "path": "/u/0/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 13
    },
    {
        "domain": ".keep.google.com",
        "expirationDate": 1562571904,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__utmz",
        "path": "/u/0/",
        "sameSite": "no_restriction",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "40529592.1545898150.1.1.utmcsr=google.com|utmccn=(referral)|utmcmd=referral|utmcct=/keep/",
        "id": 14
    }
];
